CREATE TABLE IF NOT EXISTS searchKeyword (
    keyword VARCHAR(1000) PRIMARY KEY,
    view_cnt INT DEFAULT 1,
    insert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
